#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config window_placement             first_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config window_border                off
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config external_bar all:27:0

yabai -m config layout bsp
yabai -m config top_padding 20
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 10

yabai -m space 1 --label code
yabai -m space 2 --label chrome
yabai -m space 3 --label dbeaver
yabai -m space 4 --label postman
yabai -m space 5 --label other
yabai -m spac 6 --label discord

yabai -m rule --add app="^Kitty$" space=code
yabai -m rule --add app="^Chromium$" space=chrome
yabai -m rule --add app="^DBeaver$" space=dbeaver
yabai -m rule --add app="^Postman$" space=postman
yabai -m rule --add app="^Discord$" space=discord

yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"e
